USE [master]
GO

/****** Object:  Database [InvoiceDatabaseBGM]    Script Date: 6.5.2024. 23:12:12 ******/
CREATE DATABASE [InvoiceDatabaseBGM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InvoiceDatabaseBGM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\InvoiceDatabaseBGM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'InvoiceDatabaseBGM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\InvoiceDatabaseBGM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InvoiceDatabaseBGM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET ARITHABORT OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET RECOVERY FULL 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET  MULTI_USER 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET QUERY_STORE = OFF
GO

ALTER DATABASE [InvoiceDatabaseBGM] SET  READ_WRITE 
GO


